### ISSUE TITLE
Design a general way to set the context in some nodes

### ISSUE THREAD

**Issue by pablogsal** [gvanrossum/pegen#103]
For some nodes, the context (`ctx`) needs to be assigned correctly (and in some cases, this may involve a recursive traversal). Currently, we only have a helper `expr_ty store_name(Parser *p, expr_ty load_name)` to assign `Store` context to names, but we need a more general solution.

The following cases for an `expr_ty` need to be handled:

* `Attribute_kind`
* `Subscript_kind`
* `Starred_kind`
* `Name_kind`
* `List_kind`
* `Tuple_kind`
* handle forbidden names (default branch).

The relevant code in CPython lives in:

https://github.com/python/cpython/blob/master/Python/ast.c#L1124

**Comment by gvanrossum** [comment]
I'd like to avoid recursive traversal for this, at least in the helpers.

There *appear* to be six context values. https://github.com/python/cpython/blob/master/Parser/Python.asdl#L94 says:
```
    expr_context = Load | Store | Del | AugLoad | AugStore | Param
```
But `set_context()` explicitly forbids using `AugLoad` and `AugStore`, and I can't find where `Param` is set -- the compiler seems to always reject it, so I think it's also vestigial.

(Maybe we can kill the last three from the CPython source? I could not get come up with an example where `ast.dump(ast.parse(...))` uses contexts other than the first three.)

Let's assume we only have the first three of these to worry about. `Load` is the default, that leaves `Store` and `Del`. Unlike CPython, we don't have to parse assignment targets as expressions first and then recursively change them to targets. Instead, we parse them directly in the grammar using the cluster of rules under `star_targets`. What if we just added a few more rules `del_targets`, `del_target` etc., using the same structure? And then the `NAME` alternatives in `del` rules could call the helper that's currently called `_del_name()`.

The set of rules used here is a bit complex, due to the various allowances for `*stuff`. Fortunately `del` doesn't allow that, so we'd only have to replicate `targets`, `target`, `t_atom`, `t_tail`, `attr_tail`, and `index_tail`. (Note that IIUC the `| NAME` alternative for `t_atom` should call `store_name(). In fact the actions for all of these are wrong -- that's what the TODO comment is about.)

**Comment by gvanrossum** [comment]
Oh, there's another wrinkle. The rule for `target` uses `t_tail*` and `t_tail+`, but only the last tail item should become a `Store` or `Del`. Expect lots of fun here. (Not.)

**Comment by lysnikolaou** [comment]
Do you think #132 is enough to close this?

**Comment by gvanrossum** [comment]
Yeah, this is handled now.
