### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#149]
Now that #47 is closed and actions for `simpy.gram` are ready, I think it'd be helpful to gather thoughts on what's coming next and maybe open issues etc. Here are some things I think are essential:

1. Add support for f-strings (probably still not a high priority).
2. Make `simpy_cpython` pass with `TESTFLAGS=-stt`.
3. Write scripts, in order to measure time and space consumption and compare it with `pgen`.
4. Begin doing optimisation refactorings: One thought that has been brought up is the automatic insertion of cut operations in the grammar, but I guess we will have to keep iterating more on this.
5. Possibly publish the parser on PyPI. (?)
6. Pitch the project to the core-dev team, gather feedback and if all goes well, start integrating the parser into CPython as an alternate parser which can be enabled through a command-line argument.

Have I missed something important?

**Comment by gvanrossum** [comment]
I presume (1) is a prerequisite for (2), since the stdlib is surely using f-strings.

But I think (3) and (4) are the most important. We may have to profile the code in pegen.c carefully.

One possible radical option for optimization would be to do away with the the current approach for code generation, and design a parsing automaton instead for which we can generate much simpler instructions (somewhat like the old pgen, but with more opcodes). The actions would remain as fragments of C code. I can elaborate if you're interested -- but we should postpone this until we have a good idea about the performance (both time and memory) and are out of low-hanging fruit for optimizations.

I think there's no need for (5), but once we have timing information we should begin (6). Hopefully we can pitch this in person at the Language Summit, which will be held on the Wednesday before the conference (April 15 IIRC). If you can, I recommend planning to attend. (Registration for the summit hasn't started yet, I will keep you in the loop.)

**Comment by pablogsal** [comment]
> I presume (1) is a prerequisite for (2), since the stdlib is surely using f-strings.

I am working currently on this but there is considerable code to port and it needs to be treated carefully because there are some tricky parts (as for example calling the parser itself on pieces of the fstring). Will keep you updated if I need help or if I find some blocker.

> But I think (3) and (4) are the most important. We may have to profile the code in pegen.c carefully.

For measuring our progress we could use https://github.com/airspeed-velocity/asv. It can generate nice graphs of speed per commit. For example:

https://pandas.pydata.org/speed/pandas/

> I think there's no need for (5), but once we have timing information we should begin (6). Hopefully we can pitch this in person at the Language Summit, which will be held on the Wednesday before the conference (April 15 IIRC). If you can, I recommend planning to attend. (Registration for the summit hasn't started yet, I will keep you in the loop.)

We need to submit a proposal once the call for proposals opens. I think this is very interesting to discuss so hopefully the organizers (Mariatta and Łukasz?) will select it :)

**Comment by gvanrossum** [comment]
Before we invest in airspeed-velocity we should have a benchmark we care about.

Can that package work retrospectively? I am interested in how we lost speed since the London sprint.

**Comment by pablogsal** [comment]
> Can that package work retrospectively? I am interested in how we lost speed since the London sprint.

As far as I remember, yes: you can run a benchmark over an arbitrary range of commits.

**Comment by lysnikolaou** [comment]
> I am working currently on this but there is considerable code to port and it needs to be treated carefully because there are some tricky parts (as for example calling the parser itself on pieces of the fstring). Will keep you updated if I need help or if I find some blocker.

I tried out implementing this and exactly this point was already a blocker for me, so good luck! Please let me know, in case we can split the work somehow.

**Comment by lysnikolaou** [comment]
> I am interested in how we lost speed since the London sprint.

I would guess that adding `get_last_non_whitespace_token` in #121 could be the reason. The loop in there should return early most of the time, but since we are calling it so often, it call still make a difference.

**Comment by pablogsal** [comment]
I think we can start by designing some granular benchmark scenarios (time and memory) of things we care about (we could start by using our existing cases for AST validation to understand what is more expensive to parse) and maybe some edge situations. Once we have that, should be easy to run them back in time to understand the evolution per-commit and it will help measuring future improvements.

**Comment by gvanrossum** [comment]
> I would guess that adding get_last_non_whitespace_token in #121 could be a reason.

Hm, not really. Before that commit, I measure about 4.9 seconds for the cpython directory (`make simpy_cpython`, best of three). After it, I measure around 5.0. But at master's HEAD, it's over 6.9 seconds!

**Comment by lysnikolaou** [comment]
> we could start by using our existing cases for AST validation to understand what is more expensive to parse

Opened #150 for this.

**Comment by lysnikolaou** [comment]
> Hm, not really. Before that commit, I measure about 4.9 seconds for the cpython directory (`make simpy_cpython`, best of three). After it, I measure around 5.0. But at master's HEAD, it's over 6.9 seconds!

Wasn't really expecting that. I'm curious now!

**Comment by lysnikolaou** [comment]
Opened #157 with some local timings of `simpy_cpython` on different commits.

**Comment by gvanrossum** [comment]
Is this issue still relevant? Is this repo even still relevant? We have too many repos and trackers... Here, we-like-parser, cpython, and now lepegen.

**Comment by lysnikolaou** [comment]
I don't think it's relevant anymore. All of the steps are done and everything has been set. I'm closing this and we can talk about the multiple repos/trackers situation in chat, since I feel it's a real issue as well.

**Comment by ethanhs** [comment]
So, I was thinking about the current state of typed_ast, which is somewhat stuck with supporting only 3.7 syntax, which is a problem for mypy and a lot of linters that use typed_ast. Could pegen replace typed_ast? As I understand it, pegen supports all of the backwards compatibility that the stdlib parser supports, and on top of that, it should be much easier to ship separately? (Since it grew outside of the stdlib)

**Comment by gvanrossum** [comment]
Unfortunately that's no longer true -- extracting all the work done to make the new parser compatible with the old one destroyed the portability. So mypy etc. will have to continue the approach of using the stdlib ast for 3.8+.

**Comment by gvanrossum** [comment]
(See https://github.com/python/typed_ast/issues/118 for more discussion.)

**Comment by ethanhs** [comment]
>extracting all the work done to make the new parser compatible with the old one destroyed the portability

That's too bad :(

Just to clarify, by make compatible with the old parser, you mean the pgen based parser, not the feature compatibility stuff, yes? Also, by my recollection, the main issue with extracting the old parser from Python in 3.8 was the move to make more headers internal, and extracting all the C code the parser depended on. Does pegen suffer the same issues? I took a quick look, and it seems like it only relies on pyarena, which is easy to extract, and the tokenize stuff, which is also pretty easy. Perhaps there is something else that makes it harder.

**Comment by pablogsal** [comment]
> I took a quick look, and it seems like it only relies on pyarena, which is easy to extract, and the tokenize stuff, which is also pretty easy. Perhaps there is something else that makes it harder.

It also depends on the ast symbols in https://github.com/python/cpython/blob/master/Python/asdl.c that are not exported anymore in Python3.9 and version dependent. Copying those symbols will also make any generated AST not compatible with the `stdlib` ast. That's why we needed to do some `hacks` when comparing ASTs in the tests (https://github.com/python/cpython/blob/master/Tools/peg_generator/pegen/ast_dump.py).

**Comment by gvanrossum** [comment]
Sorry, "extracting" -> "doing". A bunch of work was done to make it link into Python 3.9 without using a dynamically loaded library. And a lot of work was done for complete compatibility on error column offsets and messages (this still ongoing). We also just stopped keeping the pegen repo in sync with the 3.9 Tools/peg_generator directory.

**Comment by ethanhs** [comment]
>It also depends on the ast symbols in https://github.com/python/cpython/blob/master/Python/asdl.c and https://github.com/python/cpython/blob/master/Python/Python-ast.c that are not exported anymore in Python3.9 and version dependent

Yeah, typed_ast relies on this too, AIUI. I don't think this would be an issue for mypy/linters because they would use it in place of `ast`. (Imagine something like `import pegen_ast as ast` at the top).

>A bunch of work was done to make it link into Python 3.9 without using a dynamically loaded library. And a lot of work was done for complete compatibility on error column offsets and messages (this still ongoing). We also just stopped keeping the pegen repo in sync with the 3.9 Tools/peg_generator directory.

Totally fair! That sounds like a lot of work for unknown benefit. At this point I'm wondering if it would still be decently easy to extract the pegen in the CPython master branch. It seems it can't be too hard (famous last words). Thank you both for the helpful information on the changes.

**Comment by gvanrossum** [comment]
It should not be impossible to extract it, but it feels like a lot of work.
There are probably several steps:
- Copy all the changes to the code generators (I think there are a few
changes to the metagrammar too, e.g. '(memo)').
- Copy the changed support code from CPython (Parser/pegen/*). This would
require renaming '_PyPegen_foo_bar' back to 'foo_bar'.
- Change the way things are built.

**Comment by ethanhs** [comment]
Btw, I did it, as Guido suggested, and it was pretty easy for the most part. The only (not really hard) part left is backporting. I think instead of backporting pegen itself, it makes more sense to require Python 3.8+ to run the parser generator, then make the generated extension compatible with Python 3.6+. I will publish a repo with what I have soon for those interested.

**Comment by gvanrossum** [comment]
Exciting! Can't wait. Hopefully we can merge back into this repo?

**Comment by ethanhs** [comment]
@gvanrossum I was actually planning on merging it into typed_ast since that has the Python 2 parsing code already, and I need to make the extension a bit different (probably based on the standard library internal API https://github.com/python/cpython/blob/03b7642265e65f198682f22648dbe6cf4fff9835/Include/internal/pegen_interface.h). But we could of course make typed_ast depend on pegen in some way.

**Comment by gvanrossum** [comment]
That’s actually a good idea. Go for it!
