### ISSUE TITLE
add argument to turn off AST generation and measure just parsing

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#160]
When refactoring PEG grammars there may be rewrites that ease code generation, but hurt the performance of the parser, because PEG is more algorithmic than denotational or functional.

The original `sympy` grammar was performant to the levels of `pgen`, and there are no theoretical reasons why `pegen` can't keep being as performant.

To measure, it's important to have a way to _only_ parse, thus the request for options that make it easy to bypass code generation in unit tests and system tests. After finding rules that are taking more than expected, reordering of clauses and/or lookaheads often return the parser to the previous performance.

(cc @gvanrossum, as discussed on email)

**Comment by gvanrossum** [comment]
To aid in the analysis, here are various timing components.

1. Parsing proper. With #162 in place, we can time this using `--skip-actions`.

2. Parsing plus AST generation. This can currently only be tested by editing `data/simpy.gram` to change the `start` rule to be type-less, i.e. remove the `[mod_ty]` from the `start` rule.

3. Parsing, AST generation, and converting the AST to Python objects (using `PyAST_mod2obj()`). This is what's timed by default, but it's not very realistic, since in real life we never convert the AST to Python objects, we just compile the internal form of the AST to bytecode.

I propose that we also add a flag somewhere so we can easily time (2). This flag would basically force the `mode` argument to `run_parser()` (in `pegen/pegen.c`) to zero.
