### ISSUE TITLE
pretty-print

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#161]
It would be great if there was a tool that produced documentation-ready grammars from the AST generating grammar.

Also important is that as new people come into the project to help with the grammar refactoring towards AST generation, there is one-and-only one way to rightly format the grammar (as with Python code, and as in CPython C code).

A `pretty-printer` can solve the above, and would take a short time to write, because there's an OO representation and walkers/visitors for all grammars.

(cc @gvanrossum as discussed by email)

**Comment by gvanrossum** [comment]
I wonder if `str(g)` isn't good enough. This pretty-prints the grammar, omitting types, actions and rule names, and automatically deciding whether to use the compact or long form. For example, it turns
```
import_stmt[stmt_ty]: import_name | import_from
import_name[stmt_ty]: 'import' a=dotted_as_names { _Py_Import(a, EXTRA) }
# note below: the ('.' | '...') is necessary because '...' is tokenized as ELLIPSIS
import_from[stmt_ty]:
    | 'from' a=('.' | '...')* !'import' b=dotted_name 'import' c=import_from_targets {
        _Py_ImportFrom(b->v.Name.id, c, seq_count_dots(a), EXTRA) }
    | 'from' a=('.' | '...')+ 'import' b=import_from_targets {
        _Py_ImportFrom(NULL, b, seq_count_dots(a), EXTRA) }
import_from_targets[asdl_seq*]:
    | '(' a=import_from_as_names ')' { a }
    | import_from_as_names
    | '*' { singleton_seq(p, alias_for_star(p)) }
import_from_as_names[asdl_seq*]:
    | a=','.import_from_as_name+ [','] { a }
import_from_as_name[alias_ty]:
    | a=NAME b=['as' z=NAME { z }] { _Py_alias(a->v.Name.id,
                                               (b) ? ((expr_ty) b)->v.Name.id : NULL,
                                               p->arena) }
dotted_as_names[asdl_seq*]:
    | a=','.dotted_as_name+ { a }
dotted_as_name[alias_ty]:
    | a=dotted_name b=['as' z=NAME { z }] { _Py_alias(a->v.Name.id,
                                                      (b) ? ((expr_ty) b)->v.Name.id : NULL,
                                                      p->arena) }
dotted_name[expr_ty]:
    | a=dotted_name '.' b=NAME { join_names_with_dot(p, a, b) }
    | NAME
```
into
```
import_stmt: import_name | import_from
import_name: 'import' dotted_as_names
import_from:
    | 'from' (('.' | '...'))* !'import' dotted_name 'import' import_from_targets
    | 'from' (('.' | '...'))+ 'import' import_from_targets
import_from_targets: '(' import_from_as_names ')' | import_from_as_names | '*'
import_from_as_names: ','.import_from_as_name+ ','?
import_from_as_name: NAME ['as' NAME]
dotted_as_names: ','.dotted_as_name+
dotted_as_name: dotted_name ['as' NAME]
dotted_name: dotted_name '.' NAME | NAME
```

**Comment by goodmami** [comment]
> documentation-ready grammars

[pygments](https://github.com/pygments/pygments/) recently merged my PR (pygments/pygments#1336) for syntax highlighting of PEG grammars. Being part of pygments makes it available for Sphinx-based documentation, which is why I thought it might be relevant for this issue.

I did not write the lexer for pegen specifically, but for Bryan Ford's original PEG syntax with some accommodations (see below). The simplified grammar from `str(g)` in the previous comment looks like this (using the RTD default colors):

![pegen highlighted](https://user-images.githubusercontent.com/1428419/72716840-e2486e00-3bad-11ea-8009-83d63a28a428.png)

Note the following:

* I made `:` and `|` lex as operators in addition to the standard `<-` and `/`, respectively
* `.` is a keyword, not an operator
* I did *not* make `[` and `]` as optionality-brackets as pegen does because they are used for character classes in standard PEG syntax (notice the `['as' NAME]` is styled like a string)
* The associated file extensions include `.peg` and not `.gram`

The merged code is not yet part of a release, so you'll have to clone pygment's master branch if you want to try it out or extend it.

**Comment by gvanrossum** [comment]
@goodmami That will likely be useful for other pegen users (once there are any). I don't expect CPython itself to adopt this approach -- currently snippets of grammar are included as code blocks, and that will likely remain the case.

**Comment by apalala** [comment]
I agree that `__str()__` should be good enough. But the OP's intention was to have a pretty-printer with options for, at least, documentation-ready grammars (devoid of semantic actions, lookaheads, cut, etc.). 

Having a tool to output the grammar in different formats could allow for ANTLR-ready output, etc.

**Comment by gvanrossum** [comment]
All this sounds like a distraction for the true purpose of this repo, which is to build a better parser for *Python* that can be adopted by CPython 3.9 or 3.10.
