### ISSUE TITLE
Strings in AST should not include quotes

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#163]
I just discovered that `make test` prints the output as
```
"Hello ""world"
```
Using bisection I found that it (correctly) printed
```
Hello world
```
before 3be531c (#133). That PR refactored string parsing thoroughly. I presume something went wrong. @pablogsal Can you look into this?

**Comment by pablogsal** [comment]
> Can you look into this?

I did a preliminary investigation and I found that this is something that happens only outside `simpy.gram`. The reason is that the string handling functions for "STRINGS+" need the quotes and the prefixes intact to correctly produce the final string. In simpy.gram this is fine because all strings go trough these pipelines and the final quoting is correct but any grammar that is using `STRING` directly will receive the unrefined string.

Note that even before  3be531c the behaviour of `string_token` is incorrect: If you change `data/cprog.txt` to have prefixes:

```diff
--- a/data/cprog.txt
+++ b/data/cprog.txt
@@ -1,5 +1,5 @@
 if 1:
-    print("Hello " + "world")
+    print(u"Hello " + "world")
     if 0:
```

then `make test` prints the output as (note the initial quote):

```
"Hello world
```

Here is the general problem:

* `STRING` produces code that calls `string_token()` and that produces an ast constant (which is valid by itself) and that *should* not have quotes or prefixes. Currently this nodes contain the RAW string (needed for the second phase) and before commit 3be531c  they contained a string with stripped quotes (but not always correct as the previous example shows).

* When we parse `STRINGS+` we receive multiple constant nodes result of calling  `string_token()` 
 over them but we need the quotes and the prefixes intact to properly produce a final string: a new constant node with the strings joined (this is if we want to reuse the previous machinery as much as possible).

A solution that I can think of initially is somehow producing fully-correct AST nodes in `string_token()` and from them recostructing the original raw string before passing that down to the functions that handle `STRINGS+` (`concatenate_strings() and friends). Care must be taken into consideration as these boxing-unboxing operations can impact performance for no gain (as we are doing operations that need to be undone in later steps).

@gvanrossum @lysnikolaou What do you think the best approach here should be?

**Comment by gvanrossum** [comment]
To summarize, the issue seems to be that `concatenate_strings()` takes a list of `STRING` nodes *with* quotes and returns a single node *without* quotes. And `make test` doesn't use `data/simpy.gram`, it uses `data/cprog.gram`, which doesn't call `concatenate_strings()`.

So maybe it's a non-problem and we should just add a call to `concatenate_strings()` to `data/cprog.gram`?

**Comment by gvanrossum** [comment]
(Or better, switch to using the simpy grammar in the tests run from the Makefile. See #164.

**Comment by pablogsal** [comment]
In #165 I found a very simple way to simplify things and solve the problem
