### ISSUE TITLE
Add actions to data/simpy.gram

### ISSUE THREAD

**Issue by gvanrossum** [gvanrossum/pegen#47]
There's a complete Python grammar in `data/simpy.gram`, but it is lacking actions.

OTOH there are actions (written in C) for a very small subset in `data/cprog.gram` -- these are tested by the `Makefile` targets `test`, `compile`, `dump` and `time`. The actions construct accurate AST nodes.

We should add actions to `simpy.gram` modeled after those in `cprog.gram`.

This will likely require refactoring the grammar in `simpy.gram`.

**Comment by gvanrossum** [comment]
Before we start refactoring the grammar, we should have tests to ensure that the refactoring doesn't break the validity of the grammar -- see #48.

In order to verify that the actions create the correct AST, we can compare the generated AST with the "official" AST, for example as follows:
```py
import ast
import pegen.parse

def compare(source: str):
    expected = ast.parse(source)
    actual = pegen.parse.parse_string(source)
    assert ast.dump(actual) == ast.dump(expected)
```
Initially we should do this only for some carefully constructed test files that contain only grammar rules for which we already have actions. (We could create a separate directory full of such test files and add one or more each time we add new actions.)

Once we have actions everywhere we should be able to run this over all of the stdlib.

**Comment by apalala** [comment]
With PEG, parsing can start at any rule, which means that we can progressively test the generated AST with Python code fragments through unit tests, and add AST verification to the `test_parse_directory.py` later.

Because the grammar is large, we need a way to split the work to avoid merge conflicts as much as possible. 

Does `ast.c` support passing `NULL` for child nodes? If not, we can make the parser default to returning the AST for `None` when a rule produces no AST. That would allow one of us to work on, say, statements, while the other is working on expressions. The cost will be that many unit tests will have to be updated with each newly generated AST.

**Comment by gvanrossum** [comment]
According to cpython/Parser/Python.asdl, only arguments flagged with `?` can be left NULL. Probably in most cases `None` will work, so that's a good idea! It should be easy to execute.
