### ISSUE TITLE
Validate implementation of the 'cut' operator

### ISSUE THREAD

**Issue by apalala** [gvanrossum/pegen#49]
The 'cut' operator serves two purposes in PEG (and other types of grammars):

1. It commits the parser to the current alternative, so further alternatives will not be tried.

The above is important because a parser must deal with valid programs, and _also_ with not-valid ones. The `cut` operator is the best way to make the parser commit to failure fast (an intentionally ambiguous pseudo-Python source could make the parser backtrack a lot).

2. It allows to prune the memoization cache, saving memory.

**Comment by gvanrossum** [comment]
Maybe we should just insert *cut* operators in every rule that starts with a unique token.

**Comment by apalala** [comment]
We need to think about a `C` implementation for 'cut' first. In TatSu, it is embedded in one of the context managers handling for the `with` statements, so it's "kind of magic".

**Comment by apalala** [comment]
I thought of one. Currently, `pegen` generates:

```python
if (True
and some_rule_ref()
and ...
):
```
It would be enough if it generated:
```python
if (not cut
and some_rule_ref()
and ...
):
```
Then a 'cut' expression could be implemented with something like:

```python
cut = self.cut()  # cleanup, always True
```

**Comment by gvanrossum** [comment]
I believe the C generator has an implementation of `cut` already. It only generates code when `cut` is actually used. Try it!

**Comment by apalala** [comment]
I looked at the implementation of `cut` in the generated C, and it is not correct. The 'cut' state must be in a stack with one entry for each alternative (`|`).

An example:
```ebnf
small_stmt: ( return_stmt | import_stmt | 'pass' | raise_stmt | yield_stmt | assert_stmt | del_stmt | global_stmt | nonlocal_stmt
            | assignment | expressions
            )
```
It should be possible to write:

```ebnf
if_stmt: 'if' ~ full_expression ':' block elif_block* [else_block]
```
And have that `~` have an effect on `small_stmt`.

Either that, or pollute the grammar with lookaheads:

```ebnf
small_stmt: ( &"return" ~ return_stmt | &"import" ~ import_stmt | ...
```

**Comment by apalala** [comment]
I think that the `if` version of checking for 'cut' is clearer, more so when there are several alternatives:

```C
    int mark = p->mark;
    push_cut(p)
    // return_stmt
    if (!p->cut  // always false for the first alternative/option
        && (return_stmt_var = return_stmt_rule(p))
    ) {
        res = return_stmt_var;
        insert_memo(p, mark, small_stmt_type, res);
        goto done;
    }
    p->mark = mark;
    // import_stmt
    if (!p->cut
        && (import_stmt_var = import_stmt_rule(p))
    ) {
        res = import_stmt_var;
        insert_memo(p, mark, small_stmt_type, res);
        goto done;
    }
...
    p->mark = mark;
    res = NULL;
  done:
    pop_cut(p)
    insert_memo(p, mark, small_stmt_type, res);
    return res;
```
In any part of the parser, a `~` expression can be implemented by:

```C
p->cut = 1
```

**Comment by gvanrossum** [comment]
Oh, it seems I have misunderstood the meaning and use of ‘cut’. I guess we should fix the Python generator first, and write tests that validate his behavior. 

Another (separate) idea might be to calculate FIRST (and FOLLOW) sets and use those to automatically accelerate those parts of the parser where the grammar is LL(1).

**Comment by apalala** [comment]
Another approach is to pass `*cut` to each function implementing a rule.

```c
// stmt[stmt_ty]: compound_stmt | simple_stmt
static stmt_ty
stmt_rule(Parser *p, int *cut)
{
    stmt_ty res = NULL;
    if (is_memoized(p, stmt_type, &res))
        return res;
    int mark = p->mark;
    stmt_ty compound_stmt_var;
    stmt_ty simple_stmt_var;
    // *** push on the cut stack
    int cut_var = 0;
    cut = &cut_var;  
    // *** 
    // compound_stmt
    if (!cut &&
        (compound_stmt_var = compound_stmt_rule(p, cut))
    ) {
        res = compound_stmt_var;
        insert_memo(p, mark, stmt_type, res);
        goto done;
    }
    p->mark = mark;
    // simple_stmt
    if (!cut &&
        (simple_stmt_var = simple_stmt_rule(p, cut))
    ) {
        res = simple_stmt_var;
        insert_memo(p, mark, stmt_type, res);
        goto done;
    }
    p->mark = mark;
    res = NULL;
  done:
    insert_memo(p, mark, stmt_type, res);
    return res;
}
```
And then:

```c
// if_stmt[stmt_ty]: 'if' c=expr ':' t=suite e=else_clause? { _Py_If ( c , t , e , EXTRA ( c , c ) ) }
static stmt_ty
if_stmt_rule(Parser *p, int *cut)
{
    stmt_ty res = NULL;
    if (is_memoized(p, if_stmt_type, &res))
        return res;
    int mark = p->mark;
    expr_ty c;
    void *e;
    void *keyword;
    void *literal;
    asdl_seq* t;
    // 'if' c=expr ':' t=suite e=else_clause? { _Py_If ( c , t , e , EXTRA ( c , c ) ) }
    if (
        (keyword = keyword_token(p, "if"))
        &&
        (*cut = 1)
        &&
        (c = expr_rule(p))
        &&
        (literal = expect_token(p, 11))
        &&
        (t = suite_rule(p))
        &&
        (e = else_clause_rule(p), 1)
    ) {
        res = _Py_If ( c , t , e , EXTRA ( c , c ) );
        insert_memo(p, mark, if_stmt_type, res);
        goto done;
    }
    p->mark = mark;
    res = NULL;
  done:
    insert_memo(p, mark, if_stmt_type, res);
    return res;
}
```

**Comment by apalala** [comment]
Missing from the above is the pruning of cached memos...

**Comment by gvanrossum** [comment]
I don't like passing an extra argument to each parsing method, but I don't like implementing an additional stack either. So I propose to use a local variable `save_cut` where the previous value of `p->cut` is saved in functions that touch it. That way we'd be using the C stack, which exists anyway.

**Comment by apalala** [comment]
A problem with the last approach and the current `c_generator` is that a _'cut' context_ is required also for optionals and closures. See implementation for choices in #53.

**Comment by gvanrossum** [comment]
I still have a question about *cut*. From your explanation a long time ago [on Discourse](https://discuss.python.org/t/preparing-for-new-python-parsing/1550/43?u=guido) I understood that cut acts *locally*. But your recent comments here make me think that it's not that simple. Have you changed your mind, or did I misunderstand your intention?

Is there a description of on *cut* from academia, or at least from other sources than TatSu?

If a failure at a cut point abandons not just local alternatives but also "parent" or "caller" alternatives, doesn't that mean that cut's effect is in fact global, and failure to parse past a cut point causes the parse to fail globally? (That seems fine in the example of `if_statement`, BTW, but I don't know what other examples it would break.)

**Comment by goodmami** [comment]
> Is there a description of on cut from academia, or at least from other sources than TatSu?

I believe [Mizushima et al. 2008](http://kmizu.github.io/papers/pro_35-mizushima.pdf) originally describes it, but unless you can read academic Japanese it might not help much. [Mizushima et al. 2010](http://kmizu.github.io/papers/paste513-mizushima.pdf) (in English) describes *cut* and the automatic insertion of cut operators. The concept originally comes from Prolog (see [here](http://www.cse.unsw.edu.au/~billw/dictionaries/prolog/cut.html)). Raku (formerly Perl 6) calls it [ratcheting](https://docs.raku.org/language/grammars), such that the success of a `token` or `rule` regex (unlike a `regex` regex(?)) "locks" into place and won't backtrack.

I think cuts must act locally. From Mizushima et al. 2010, consider this quote (emphasis mine), where `↑` is their cut operator:

> ```
> S ← "if" ↑ "(" E ")" S ("else" S)?
>   / "while" ↑ "(" E ")" S
>   / "print" ↑ "(" E ")" S
>   / "set" I "=" E ";";.
> ```
> The above PEG instructs the parser to not backtrack to the other choices when one of the "if", "while", or "print" succeeds by cut operators. Note that *a cut operator is meaningless in the last choice because no further choices are left*.

If cuts acted globally, then a cut in the last choice would not be "meaningless", as it could prevent backtracking to a "parent" rule.

Also consider the following, where we have a small language with dicts and sets (both delimited by `{` and `}` as in Python) where dict keys must be strings and dict or set values must be strings or numbers. I'll try to use the pegen syntax (including the newer dot operator). First we can define a `value` like this:

```
value: &'"' ~ string | number
```

So if we see a `"` then the value must be a string and don't bother attempting to parse it as a number. Now consider using it as follows (leaving the definition of `string` and `number` as an exercise to the reader):

```
expr: '{' (setitems | dictitems) '}'
setitems: ','.value*
dictitems: ','.dictitem*
dictitem: string ':' value
```

If cuts prevented backtracking globally, this grammar could not then parse dictionaries, such as `{"a": 1}` because once it sees the `"` of the first `value` of `setitems` it would cut and then fail at the `:`.

**Comment by gvanrossum** [comment]
@goodmami Thanks very much for digging up those references! Your first quote convinces me that cut is meant to act locally (which is how I have implemented it).

From that quote it also seems clear that cut is primarily intended by the authors as an optimization -- the accepted language doesn't change without those cut operators. Apparently packrat parsing is not quite efficiently by itself as one would have hoped from reading the original article (about packrat parsing), and cut can give some of that back. We may have to use it to recover some parsing speed for the Python grammar we're developing, which is aiming to compete with the current LL(1) parser (pgen).

But there may still be a need for a more sophisticated version of cut. This is what @apalala was aiming for when he started this issue, and what he tried to implement in #53. For example, if we refactor the example language from the paper into:
```
S: if_stmt | while_stmt | print_stmt | set_stmt
if_stmt: 'if' '(' E ')' S ['else' S]
while_stmt: 'if' ( E ')' S
print_stmt: 'print' '(' E ')' S
set_stmt: 'set' I '=' E ';'
```
(which we might want to do for readability or for reuse of some of these rules in other contexts) then adding cut operators after the keywords wouldn't help if cut acted purely locally. The same issue would happen with parenthesized sub-alternatives. Here's maybe a plausible example:
```
stmt: expr ('=' ~ expr)?
```
where the intent is to fail parsing if there's no `expr` after the `'='` rather than just parsing a single `expr` and leaving the `=` to be rejected many attempts later. Though this one could be refactored easily into this:
```
stmt: expr '=' ~ expr | expr
```

**Comment by gvanrossum** [comment]
Also, reading further into that article, there may be something else of value for us. They proceed to describe automatic insertion of cut operators. This is an extension of the use of FIRST sets in LL(1) parser generators. Since Python is mostly LL(1) this may be most advantageous for us!

**Comment by goodmami** [comment]
Thanks for those examples and explanation; now I better understand the discussion earlier in this thread.

For the refactored example you gave, "polluting" (as @apalala calls it) the grammar with lookaheads doesn't seem so bad from a performance standpoint, assuming the lookahead expression gets memoized so you don't have to parse it again, but it does make the grammar a little uglier.

Also, I just turned up [Redziejowski, 2015](http://www.romanredz.se/papers/FI2015.pdf) (and a wealth of other papers on PEG: http://www.romanredz.se/pubs.htm), which posits two cut operators, `↓` and `↑`, which indicate the "cut points", i.e., the start and end of the pattern on which to cut. I don't immediately see a big gain in the starting cut-point but it seems like a possible solution if it could occur in another rule, like a notch on which to ratchet (or a try...except for some propagating exception), but I'm not convinced that it would be a *good* way forward. For example, what if not every caller of a rule with an end point has a start point? Beyond that, this would require yet another symbol in the grammars.

Something like `~N` to cut at `N` levels up (defaulting to 1 for `~`) seems simpler, at least:

```
stmt: expr ('=' ~2 expr)?
```

I like the idea of automatically inserting cut operators. If it's reliable and doesn't change the behavior, then the grammar writer doesn't have to think about them (except, perhaps, in the non-local case).

**Comment by gvanrossum** [comment]
Ah, by "polluting the grammar with lookaheads" you mean like this:
```
S: &'if' ~ if_stmt | &'while' ~ while_stmt | &'print' print_stmt | set_stmt
```
I guess that's acceptable, though when printing the "cleaned up" grammar (which leaves out actions, item names, and rule types) we might want to elide these as well.

A totally different trick might be for the parser generator to analyze the FIRST sets of the alternatives and create some data structure that can be used to efficiently skip alternatives based on one token -- another hybrid with LL(1).

If we're going to do an "uplevel" cut, I'd propose to spell it `~`, `~~`, `~~~`, etc., rather than `~`, `~2`, `~3`, etc. -- we're never going to need that many levels. But it seems a measure of last resort.

I like the automatic insertion of cut points, maybe @lysandros can work on this? (After all he's hoping to get a B.Sc. out of the project.)

**Comment by lysnikolaou** [comment]
@gvanrossum Sorry I didn't respond sooner. I never got a notification (Correct first name, wrong Github username used in mention :-) I can certainly work on this, although it seems that I'm gonna need a bit of guidance, in order to 100% understand the whole thing. I'm gonna spend a few days reading up on the topic of automatic insertion of cuts and we can then discuss a bit more into detail if we want to go ahead and start implementing such a feature. I think it can also be in the optimization phase of the project (if there's such a phase), after we're done with #47.

**Comment by gvanrossum** [comment]
Yeah, once we've got all the actions in place and `make simpy_cpython TESTFLAGS=-stt` passes we can look into this. (But first we should probably do some benchmarks.)

**Comment by gvanrossum** [comment]
After some more thinking about it, I'm not convinced we should take any action here, so I'm closing this issue.

**Comment by wiltchamberian** [comment]
good discussion! in my opinion, cut is essentially a manual First set. The first set are calculated automatically by LL1 but cut is just used to do the same thing manually and explictly.
