### ISSUE TITLE
How to differentiate between Load and Store for NAMEs?

### ISSUE THREAD

**Issue by lysnikolaou** [gvanrossum/pegen#79]
I got to implementing the actions for `while` and `for` and found out that, upon parsing a NAME, `name_token` gets called, which always uses `Load`. Except for the quick workaround

```
target: a=NAME { _Py_Name(a->v.Name.id, Store, EXTRA_EXPR(a, a)) }
```
there is unfortunately no other way to use Store for a NAME.

What do you think is the best way to implement this?

**Comment by gvanrossum** [comment]
Create a helper function that takes a Load name object as input and constructs an otherwise equivalent Store name object?

**Comment by lysnikolaou** [comment]
> Create a helper function that takes a Load name object as input and constructs an otherwise equivalent Store name object?

Or changes the `ctx` field in place?

What I haven't understood though is if there is an occurrence of `NAME` in the grammar, which could be either one, according to where the rule got called from.

**Comment by gvanrossum** [comment]
Because of the way the packrat parser cache works, you shouldn't modify anything that's been cached in place, because a backtrack could cause it to be reinterpreted the other way. This is not hypothetical: if you parse a simple expression like `x`, the parser first parsers it as a target, then finds there's no `=` following that, then backtracks and reinterprets it as an expression.

**Comment by lysnikolaou** [comment]
Understood! Hadn't thought about that till now.
